In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student_performance_interactions (1).csv to student_performance_interactions (1).csv


In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import tensorflow as tf

# =========================
# =========================
# 1. LOAD DATASET
# =========================
df = pd.read_csv("student_performance_interactions (1).csv")

# Drop ID if exists
if "student_id" in df.columns:
    df = df.drop(["student_id"], axis=1)

# =========================
# 2. SPLIT FEATURES & TARGET
# =========================
y = df["grade"]
X = df.drop("grade", axis=1)

# =========================
# 3. HANDLE CATEGORICAL DATA
# =========================
# Convert categorical columns → numerical
X = pd.get_dummies(X, drop_first=True)

# Encode target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 3. TRAIN-TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# =========================
# 4. FEATURE SCALING
# =========================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================
# 5. BUILD NEURAL NETWORK
# =========================
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# =========================
# 6. TRAIN MODEL
# =========================
model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=1)

# =========================
# 7. EVALUATION
# =========================
y_pred = np.argmax(model.predict(X_test), axis=1)

print("\n✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))
print("\n📌 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# =========================
# 8. SAMPLE PREDICTION
# =========================
# =========================
# SAMPLE INPUT (original format)
# =========================
sample = {
    "previous_score": 75,
    "motivation_score": 8,
    "daily_study_hours": 3,
    "exam_anxiety_score": 4,
    "homework_completion_rate": 80,
    "attendance_percentage": 85,
    "screen_time_hours": 2,
    "sleep_hours": 7,
    "parent_education_level": "Master"
}

# Convert to DataFrame
sample_df = pd.DataFrame([sample])

# Apply same encoding
sample_df = pd.get_dummies(sample_df)

# 🔥 MOST IMPORTANT LINE
sample_df = sample_df.reindex(columns=X.columns, fill_value=0)

# Scale
sample_scaled = scaler.transform(sample_df)

# Predict
prediction = model.predict(sample_scaled)
predicted_class = np.argmax(prediction, axis=1)

# Convert back
predicted_grade = le.inverse_transform(predicted_class)

print("🎯 Predicted Grade:", predicted_grade[0])

# =========================
# 9. RISK DETECTION
# =========================
if predicted_grade[0] in ['D', 'F']:
    print("⚠️ Student is AT RISK!")
else:
    print("✅ Student is performing well")

Epoch 1/50


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


50/50 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1975 - loss: 1.9069
Epoch 2/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2825 - loss: 1.5639
Epoch 3/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4062 - loss: 1.3770
Epoch 4/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5900 - loss: 1.2136
Epoch 5/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6850 - loss: 1.0470
Epoch 6/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7063 - loss: 0.8940
Epoch 7/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7250 - loss: 0.7722
Epoch 8/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7387 - loss: 0.6864
Epoch 9/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7487 - loss: 0.6267
Epoch 10/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7675 - loss: 0.5845
Epoch 11/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.5508
Epoch 12/50
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7912 - loss: 0.5241


7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 

✅ Accuracy: 0.94

📊 Classification Report:
               precision    recall  f1-score   support

           0       0.88      1.00      0.93        21
           1       0.97      0.83      0.90        36
           2       0.93      0.94      0.93        68
           3       0.95      0.97      0.96        61
           4       1.00      1.00      1.00        14

    accuracy                           0.94       200
   macro avg       0.94      0.95      0.94       200
weighted avg       0.94      0.94      0.94       200


📌 Confusion Matrix:
 [[21  0  0  0  0]
 [ 3 30  3  0  0]
 [ 0  1 64  3  0]
 [ 0  0  2 59  0]
 [ 0  0  0  0 14]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
🎯 Predicted Grade: D
⚠️ Student is AT RISK!
